// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package fr.treeptik.gestionprojet.builder;

import fr.treeptik.gestionprojet.model.Address;

public class AddressBuilder extends AddressBuilderBase<AddressBuilder> {
	public static AddressBuilder address() {
		return new AddressBuilder();
	}

	public AddressBuilder() {
		super(new Address());
	}

	public Address build() {
		return getInstance();
	}
}

class AddressBuilderBase<GeneratorT extends AddressBuilderBase<GeneratorT>> {
	private Address instance;

	protected AddressBuilderBase(Address aInstance) {
		instance = aInstance;
	}

	protected Address getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Integer aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCity(String aValue) {
		instance.setCity(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withStreet(String aValue) {
		instance.setStreet(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withZip(String aValue) {
		instance.setZip(aValue);

		return (GeneratorT) this;
	}
}
